# Generated by Django 3.2.6 on 2021-08-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title on main page')),
                ('github', models.CharField(max_length=50, verbose_name='github leftbar link')),
                ('telegram', models.CharField(max_length=50, verbose_name='github leftbar link')),
                ('vkontakte', models.CharField(max_length=50, verbose_name='github leftbar link')),
                ('instagram', models.CharField(max_length=50, verbose_name='github leftbar link')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='techName', max_length=30, verbose_name='short name of technology')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=20, verbose_name='bold card title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='light card subtitle')),
                ('backside_subtitle', models.CharField(max_length=100, verbose_name='light card-backside subtitle')),
                ('backside_stack', models.CharField(max_length=50, verbose_name='light card-backside stack')),
                ('github_link', models.CharField(max_length=100, verbose_name='github link')),
                ('direct_link', models.CharField(max_length=100, verbose_name='direct link')),
            ],
            options={
                'verbose_name': 'Work Card',
                'verbose_name_plural': 'Work Cards',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('tech_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Technology_id_fk', to='portfolio.technology', verbose_name='Technology')),
            ],
        ),
    ]
