# Generated by Django 3.2.6 on 2021-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tech_id',
        ),
        migrations.AddField(
            model_name='skill',
            name='tech_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='Technology_Skill', to='portfolio.Technology', verbose_name='Technology'),
        ),
    ]
