# Generated by Django 3.2.6 on 2021-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='name',
            field=models.CharField(default='techName', max_length=30, verbose_name='short name of technology'),
        ),
    ]
