# Generated by Django 3.2.6 on 2021-08-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technology_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work Card', 'verbose_name_plural': 'Work Cards'},
        ),
    ]
