# Generated by Django 3.2.6 on 2021-08-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210817_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='background_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='linear gradient for card. Put code bgc: ....'),
        ),
    ]
