# Generated by Django 3.2.6 on 2021-08-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_work_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tech_id',
        ),
        migrations.AddField(
            model_name='skill',
            name='tech_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.technology', verbose_name='techs'),
        ),
    ]
