# Generated by Django 3.2.6 on 2021-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210827_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tech_id',
        ),
        migrations.AddField(
            model_name='skill',
            name='tech_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='Technology_Skill', to='portfolio.Technology', verbose_name='Technology'),
        ),
    ]
